name: Smee
description: Posts webhook payloads to Smee.io to help debug GitHub Action runs
runs:
  using: node12
  main: index.js
branding:
  icon: activity
  color: red
inputs:
  channel:
    description: The Smee channel to use. By default, it will use the ID of the repository.
outputs:
  url:
    description: The full URL that this action is sending payloads to.
